### ISSUE TITLE
你好 选项卡切换时有卡顿1秒的情况

### ISSUE THREAD

**Issue by 18667366881** [student9128/BottomNavigationBarForAndroid#1]
你好 选项卡切换时有卡顿1.2秒的情况   bug  请问如何解决一下 谢谢

**Comment by student9128** [comment]
是demo里又卡顿现象吗？哪个组合？

**Comment by 18667366881** [comment]
如果在第一个组合中 显示列表(recyclerview)  切换的时候会丢失原来的数据（第一个组合+ fragment+viewpage）  网上找了一些资料  缓存也不能用  还是有卡一下的问题
