### ISSUE TITLE
大佬，请教一下TabLayout+ViewPager遇到问题

### ISSUE THREAD

**Issue by phonegg** [student9128/BottomNavigationBarForAndroid#3]
在fragment中 调用onResume  ，刚进来第1个和第2个的fragment的onResume都会执行，点击第2个tab，发现第3个fragment的onResume方法执行了，如果需要这个预加载的方式，请问该怎么解决

**Comment by phonegg** [comment]
不需要这种预加载。。。

**Comment by student9128** [comment]
> 在fragment中 调用onResume ，刚进来第1个和第2个的fragment的onResume都会执行，点击第2个tab，发现第3个fragment的onResume方法执行了，如果需要这个预加载的方式，请问该怎么解决

这个是viewpager的功能，``` mViewPager.setOffscreenPageLimit(1);```这个方法可以设置缓存的大小

**Comment by student9128** [comment]
不需要的话就在framgent里面设置懒加载，可见的时候才去加载，Viewpager最低是1。这个网上也有方法，你搜搜这个``setUserVisibleHint``

**Comment by phonegg** [comment]
好的谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Kevin"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月21日(星期四) 中午11:28
收件人:&nbsp;"student9128/BottomNavigationBarForAndroid"<BottomNavigationBarForAndroid@noreply.github.com&gt;;
抄送:&nbsp;"晚风"<331388582@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [student9128/BottomNavigationBarForAndroid] 大佬，请教一下TabLayout+ViewPager遇到问题 (#3)




不需要的话就在framgent里面设置懒加载，可见的时候才去加载，Viewpager最低是1。这个网上也有方法，你搜搜这个setUserVisibleHint
